import 'package:flutter/material.dart';
import 'package:get/get.dart';

class Languages extends Translations {
  static const List<Locale> supportedLocales = [
    Locale('en'),
    Locale('ko'),
  ];

  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
      // Common
      'settings': 'Settings',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'share': 'Share',
      'reset': 'Reset',
      'done': 'Done',
      'ok': 'OK',
      'yes': 'Yes',
      'no': 'No',
      'error': 'Error',
      'success': 'Success',
      'loading': 'Loading...',
      'no_data': 'No data',
      'dark_mode': 'Dark Mode',
      'language': 'Language',
      'about': 'About',
      'version': 'Version',
      'rate_app': 'Rate App',
      'privacy_policy': 'Privacy Policy',
      'remove_ads': 'Remove Ads',
      'premium_title': 'Premium',
      'premium_subtitle': 'Remove ads, unlock all features, and stay focused.',
      'premium_benefits': 'Premium Benefits',
      'premium_benefit_remove_ads': 'Remove ads',
      'premium_benefit_unlimited': 'Use all features without limits',
      'premium_benefit_statistics': 'View additional statistics',
      'premium_plan_title': 'Choose a plan',
      'premium_plan_weekly': 'Weekly',
      'premium_plan_weekly_desc': '1 week premium access',
      'premium_plan_monthly': 'Monthly',
      'premium_plan_monthly_desc': '30 days premium access',
      'premium_plan_yearly': 'Yearly',
      'premium_plan_yearly_desc': '365 days premium access',
      'premium_purchase': 'Start Premium',
      'premium_restore': 'Restore Purchase',
      'premium_owned': 'Premium is active',
      'premium_purchase_note': 'If your payment is completed, purchase will be restored automatically after app restart.',
      'purchase_error': 'Purchase Error',
      'purchase_unavailable': 'In-app purchase is not available now.',
      'purchase_failed': 'Purchase failed. Please try again.',
      'restore_error': 'Restore failed. Please try again.',
      'purchase_success': 'Purchase Completed',
      'premium_ready': 'Premium is now active.',
      'send_feedback': 'Send Feedback',
      'more_apps': 'More Apps',
      'open_history': 'History',
      'open_stats': 'Stats',
      'clear_all': 'Clear All',
      'refresh': 'Refresh',
      'no_history': 'No history',
      'unknown_event': 'Unknown Event',
      'history_subtitle': 'Screen: @screen / Route: @route',
      'total_events': 'Total Events',
      'today_events': 'Today',
      'week_events': 'This Week',
      'unique_routes': 'Routes',
      'unique_screens': 'Screens',
      'top_events': 'Top Events',

      // App
      'app_name': 'Word Guess',

      // Home
      'mode_daily': 'Daily',
      'mode_infinite': 'Infinite',
      'home_title': 'Word Guess',
      'home_subtitle': 'Guess the 5-letter word in 6 tries!',
      'play_daily': 'Daily Challenge',
      'play_infinite': 'Infinite Mode',
      'play_once_per_day': 'One challenge per day',
      'keep_playing': 'Keep playing without limit',
      'category_label': 'Category',
      'cat_general': 'General',
      'cat_animals': 'Animals',
      'cat_food': 'Food',
      'cat_countries': 'Countries',
      'stats_title': 'Your Stats',

      // Game
      'hint': 'Hint',
      'new_game': 'New Game',
      'new_game_confirm': 'Start a new game? Current progress will be lost.',
      'word_too_short': 'Not enough letters',
      'not_in_word_list': 'Not in word list',
      'hint_letter': 'Position @{pos} is @{letter}',
      'no_hints_left': 'No hints left',

      // Result
      'result_win': '?럦 You Won!',
      'result_lose': '?삟 Game Over',
      'result_win_sub': 'Solved in @{n}/6 guesses',
      'result_lose_sub': 'The word was @{word}',
      'play_again': 'Play Again',
      'next_word': 'Next word in',

      // Stats
      'stat_played': 'Played',
      'stat_winrate': 'Win %',
      'stat_streak': 'Streak',
      'stat_max_streak': 'Best',
    },
    'ko': {
      // 공통
      'settings': '설정',
      'save': '저장',
      'cancel': '취소',
      'delete': '삭제',
      'edit': '편집',
      'share': '공유',
      'reset': '초기화',
      'done': '완료',
      'ok': '확인',
      'yes': '예',
      'no': '아니요',
      'error': '오류',
      'success': '성공',
      'loading': '불러오는 중...',
      'no_data': '데이터 없음',
      'dark_mode': '다크 모드',
      'language': '언어',
      'about': '앱 정보',
      'version': '버전',
      'rate_app': '앱 평가',
      'privacy_policy': '개인정보처리방침',
      'remove_ads': '광고 제거',
      'premium_title': '프리미엄',
      'premium_subtitle': '광고 제거, 추가 기능 잠금 해제, 끊김 없는 이용을 제공합니다.',
      'premium_benefits': '프리미엄 혜택',
      'premium_benefit_remove_ads': '광고 제거',
      'premium_benefit_unlimited': '모든 기능 잠금 해제',
      'premium_benefit_statistics': '추가 통계 보기',
      'premium_plan_title': '요금제 선택',
      'premium_plan_weekly': '주간',
      'premium_plan_weekly_desc': '7일 프리미엄',
      'premium_plan_monthly': '월간',
      'premium_plan_monthly_desc': '30일 프리미엄',
      'premium_plan_yearly': '연간',
      'premium_plan_yearly_desc': '365일 프리미엄',
      'premium_purchase': '구매하기',
      'premium_restore': '구매 복원',
      'premium_owned': '프리미엄이 활성화됐어요',
      'premium_purchase_note': '결제가 완료되면 앱 재시작 후에도 자동으로 복원돼요.',
      'purchase_error': '구매 오류',
      'purchase_unavailable': '인앱 결제를 사용할 수 없어요.',
      'purchase_failed': '결제에 실패했어요. 다시 시도해요.',
      'restore_error': '구매 복원에 실패했어요.',
      'purchase_success': '결제 완료',
      'premium_ready': '프리미엄이 활성화됐어요.',
      'send_feedback': '피드백 보내기',
      'more_apps': '더 많은 앱',
      'open_history': '히스토리',
      'open_stats': '통계',
      'clear_all': '전체 삭제',
      'refresh': '새로고침',
      'no_history': '기록이 없습니다',
      'unknown_event': '알 수 없는 이벤트',
      'history_subtitle': '화면: @screen / 경로: @route',
      'total_events': '총 이벤트',
      'today_events': '오늘',
      'week_events': '이번 주',
      'unique_routes': '고유 경로',
      'unique_screens': '고유 화면',
      'top_events': '상위 이벤트',
      // App
      'app_name': '단어 맞추기',
      // Home
      'mode_daily': '오늘의 도전',
      'mode_infinite': '무한 모드',
      'home_title': '단어 맞추기',
      'home_subtitle': '6번 만에 5글자 단어를 맞추세요!',
      'play_daily': '오늘의 도전',
      'play_infinite': '무한 모드',
      'play_once_per_day': '하루에 한 번 도전',
      'keep_playing': '제한 없이 플레이',
      'category_label': '카테고리',
      'cat_general': '일반',
      'cat_animals': '동물',
      'cat_food': '음식',
      'cat_countries': '국가',
      'stats_title': '내 통계',
      // Game
      'hint': '힌트',
      'new_game': '새 게임',
      'new_game_confirm': '진행 중인 게임이 사라집니다. 계속할까요?',
      'word_too_short': '글자가 부족해요',
      'not_in_word_list': '단어 목록에 없어요',
      'hint_letter': '@{pos}번 위치는 @{letter}예요',
      'no_hints_left': '힌트가 없어요',
      // Result
      'result_win': '🎉 성공!',
      'result_lose': '😢 게임 오버',
      'result_win_sub': '@{n}/6번 만에 맞췄어요',
      'result_lose_sub': '정답은 @{word}였어요',
      'play_again': '다시 하기',
      'next_word': '다음 단어까지',
      // Stats
      'stat_played': '플레이',
      'stat_winrate': '승률 %',
      'stat_streak': '연속',
      'stat_max_streak': '최고',
    },
  };
}



